# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfedit < Formula
  desc "A refactoring tool for Terraform"
  homepage "https://github.com/minamijoyo/tfedit"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.0.3/tfedit_0.0.3_darwin_arm64.tar.gz"
      sha256 "298d2cd3ff040fc4a12512654fccad4fbe114af2860864ac8947b99684bacf19"

      def install
        bin.install "tfedit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.0.3/tfedit_0.0.3_darwin_amd64.tar.gz"
      sha256 "1e68d957e0317b58d6190aee979060ef681f495dff4932866229445e22a957d5"

      def install
        bin.install "tfedit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.0.3/tfedit_0.0.3_linux_arm64.tar.gz"
      sha256 "fc26728398ac8f40fcfb44d71b886c9704cce2ffc02085920674d3a0c0cfc37f"

      def install
        bin.install "tfedit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.0.3/tfedit_0.0.3_linux_amd64.tar.gz"
      sha256 "bf094fa34b015d7c7c71b566240c706e412d3f97e7c028461150909ae3722b52"

      def install
        bin.install "tfedit"
      end
    end
  end

  test do
    system "#{bin}/tfedit version"
  end
end
