# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfedit < Formula
  desc "A refactoring tool for Terraform"
  homepage "https://github.com/minamijoyo/tfedit"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.1.3/tfedit_0.1.3_darwin_arm64.tar.gz"
      sha256 "d2326dbc3d4241ea096289fc6a9e2d79472d6e9850b66c49ea397e26da1e2ed9"

      def install
        bin.install "tfedit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.1.3/tfedit_0.1.3_darwin_amd64.tar.gz"
      sha256 "230afb8149f972b42e71ddc0ff4ffe94d3a8eaac88188a53415da91028cba7d8"

      def install
        bin.install "tfedit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.1.3/tfedit_0.1.3_linux_amd64.tar.gz"
      sha256 "08ed51d0b25dfec9f0ef9f7dbcff01950e48bcd47cfef4e47faba8c2f4ae48f7"

      def install
        bin.install "tfedit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minamijoyo/tfedit/releases/download/v0.1.3/tfedit_0.1.3_linux_arm64.tar.gz"
      sha256 "5e1dbdc7f610c942695ba39558a821d3c26885b69be5a1a9fbeb2ded7654ea80"

      def install
        bin.install "tfedit"
      end
    end
  end

  test do
    system "#{bin}/tfedit version"
  end
end
